### ISSUE TITLE
Websocket dependency

### ISSUE THREAD

**Issue by thelinuxlich** [akash-joshi/rocketrpc#14]
It's a bit worrying to me depending on WS because there are frameworks doing that (LiveView, for example) and it doesn't scale well. Did you think about doing the sync with SSE?

**Comment by akash-joshi** [comment]
So, the dependency itself is on socket.io, which falls back to HTTP long-polling whenever websockets aren't available, to ensure reliability.

I've intentionally not touched the network layer myself with this library, because I want to enable the bare fundamentals of enabling client-server agnostic function calls, without dealing with all of the faff around ensuring network layer reliability.

Hope that makes sense. Let me know if you have more questions.
